version: "3.9"

services:

  redis:
    image: redis:alpine
    networks:
      - front_end_ntw
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - back_end_ntw
    secrets:
      - postgres_password
      - postgres_user
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  vote:
    image: dockersamples/examplevotingapp_vote
    ports:
      - 8080:80
    networks:
      - front_end_ntw
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
    

  result:
    image: dockersamples/examplevotingapp_result
    ports:
      - 8081:80
    networks:
      - back_end_ntw
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
    
  worker:
    image: dockersamples/examplevotingapp_worker
    networks:
      - front_end_ntw
      - back_end_ntw
    healthcheck:
      test: ["CMD-SHELL", "pidof dotnet || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5

networks:
  front_end_ntw:
  back_end_ntw:

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.0.136,rw,nfsvers=4  #you need to have nfs setup on addr 192.168.0.136 so the data can be stored properly
      device: ":/srv/nfs/swarm_data/postgres"

      #this yml will launch 5 service stack
secrets:
  postgres_password:
    external: true
  postgres_user:
    external: true